"""coactra.orchestration.work - durable work orders for agent systems."""

from coactra.orchestration.work.backends import InMemoryWorkStore, SqlWorkStore
from coactra.orchestration.work.conformance import WorkStoreReport, check_work_store_contract
from coactra.orchestration.work.domain import (
    AgentSpec,
    ApprovalRequest,
    Artifact,
    ArtifactPart,
    ArtifactRef,
    Assignment,
    Attempt,
    AttemptStatus,
    AuditContext,
    Budget,
    CapabilityDescriptor,
    CapabilityRequirement,
    CapabilitySet,
    Checkpoint,
    Deadline,
    Decision,
    DecisionOutcome,
    ElicitationRequest,
    EventEnvelope,
    ExecutionPlan,
    ExecutionReceipt,
    Lease,
    Provenance,
    ResumeToken,
    RetryPolicy,
    Scope,
    SkillSpec,
    Usage,
    WorkOrder,
    WorkStatus,
)
from coactra.orchestration.work.routing import TenantWorkStoreRouter
from coactra.orchestration.work.service import (
    InvalidTransitionError,
    LeaseError,
    WorkError,
    WorkManager,
    WorkNotFoundError,
)
from coactra.orchestration.work.store import AtomicWorkStore, ArtifactStore, AuditSink, ConflictError, WorkStore

__all__ = [
    "__version__",
    "AgentSpec",
    "ApprovalRequest",
    "Artifact",
    "ArtifactPart",
    "ArtifactRef",
    "AtomicWorkStore",
    "Assignment",
    "ArtifactStore",
    "Attempt",
    "AttemptStatus",
    "AuditContext",
    "AuditSink",
    "Budget",
    "CapabilityDescriptor",
    "CapabilityRequirement",
    "CapabilitySet",
    "Checkpoint",
    "ConflictError",
    "Deadline",
    "Decision",
    "DecisionOutcome",
    "ElicitationRequest",
    "EventEnvelope",
    "ExecutionPlan",
    "ExecutionReceipt",
    "InMemoryWorkStore",
    "SqlWorkStore",
    "InvalidTransitionError",
    "Lease",
    "LeaseError",
    "Provenance",
    "ResumeToken",
    "RetryPolicy",
    "Scope",
    "SkillSpec",
    "Usage",
    "WorkStoreReport",
    "check_work_store_contract",
    "WorkError",
    "WorkManager",
    "WorkNotFoundError",
    "WorkOrder",
    "WorkStatus",
    "WorkStore",
    "TenantWorkStoreRouter",
]

__version__ = "0.1.0"
