"""PlaybookStore — candidate/promoted playbook lifecycle.

Public API
----------
- ``PlaybookStore``        — runtime_checkable Protocol: save_candidate / promote / get / find.
- ``InMemoryPlaybookStore``— reference implementation (dict-backed, in-process).

Design (per design/2026-06-06-review-refinements.md item 5)
------------------------------------------------------------
Planner output is a CANDIDATE: it has been generated by the LLM but not yet
reviewed or validated.  A playbook must be explicitly promoted before it is
considered authoritative and returned by ``find()``.

``get(name)``  — retrieves by exact name regardless of status (candidate or promoted).
``find(goal)`` — returns a PROMOTED playbook whose name tokens overlap with *goal*
               (case-insensitive).  Candidates are invisible to ``find()``.
``promote(name)`` — transition a candidate to promoted status.
``save_candidate(playbook)`` — register a new candidate playbook.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from coactra.workflow.playbook import Playbook

__all__ = ["PlaybookStore", "InMemoryPlaybookStore"]


# ---------------------------------------------------------------------------
# Protocol
# ---------------------------------------------------------------------------


@runtime_checkable
class PlaybookStore(Protocol):
    """Structural interface for playbook persistence with candidate/promoted lifecycle."""

    def save_candidate(self, playbook: Playbook) -> None:
        """Register *playbook* as a candidate (not yet promoted)."""
        ...

    def promote(self, name: str) -> None:
        """Promote the candidate with *name* to promoted status."""
        ...

    def get(self, name: str) -> Playbook | None:
        """Return the playbook with *name* regardless of status, or ``None``."""
        ...

    def find(self, goal: str) -> Playbook | None:
        """Return a PROMOTED playbook whose name tokens overlap with *goal*, or ``None``.

        Candidates are never returned.  Matching is case-insensitive token overlap
        against the playbook name (tokenised on whitespace and hyphens).
        """
        ...


# ---------------------------------------------------------------------------
# InMemoryPlaybookStore
# ---------------------------------------------------------------------------

_CANDIDATE = "candidate"
_PROMOTED = "promoted"


def _tokenise(text: str) -> set[str]:
    """Split *text* on whitespace and hyphens, lowercase all tokens."""
    import re

    return {t.lower() for t in re.split(r"[\s\-]+", text) if t}


class InMemoryPlaybookStore:
    """In-memory reference implementation of :class:`PlaybookStore`.

    Thread-safety: none — designed for single-threaded / async-safe call patterns.
    """

    def __init__(self) -> None:
        # Maps name → (Playbook, status)
        self._store: dict[str, tuple[Playbook, str]] = {}

    def save_candidate(self, playbook: Playbook) -> None:
        """Register *playbook* as a candidate."""
        self._store[playbook.name] = (playbook, _CANDIDATE)

    def promote(self, name: str) -> None:
        """Promote the playbook with *name* from candidate to promoted.

        If *name* is not found, this is a no-op (safe to call idempotently).
        """
        entry = self._store.get(name)
        if entry is not None:
            playbook, _ = entry
            self._store[name] = (playbook, _PROMOTED)

    def get(self, name: str) -> Playbook | None:
        """Return the playbook with *name* regardless of status, or ``None``."""
        entry = self._store.get(name)
        if entry is None:
            return None
        playbook, _ = entry
        return playbook

    def find(self, goal: str) -> Playbook | None:
        """Return the first PROMOTED playbook whose name tokens overlap with *goal*.

        Matching is case-insensitive token overlap between *goal* and the playbook
        name (tokenised on whitespace and hyphens).  Candidates are never returned.
        """
        goal_tokens = _tokenise(goal)
        for playbook, status in self._store.values():
            if status != _PROMOTED:
                continue
            name_tokens = _tokenise(playbook.name)
            if goal_tokens & name_tokens:
                return playbook
        return None
